site_name: "Async Spotify"
site_description: "Async wrapper in python for the spotify api"
site_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_name: "HuiiBuh/AsyncSpotify"

nav:
  - Overview: "index.md"
  - Reference:
      - Albums: "reference/albums.md"
      - Api: "reference/api.md"
      - Artists: "reference/artists.md"
      - Authenticication: "reference/authentification.md"
      - Decorators: "reference/decorators.md"
      - Preferences: "reference/preferences.md"
      - Spotify Errors: "reference/spotify_errors.md"
      - Status Codes: "reference/status_codes.md"
      - URLs: "reference/urls.md"
  - Licence: "licence.md"

theme:
  name: "material"

extra_css:
  - custom.css

plugins:
  - search
  - mkdocstrings:
      watch:
        - src/async_spotify
