site_name: "Async Spotify"
site_description: "Async wrapper in python for the spotify api"
site_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_name: "HuiiBuh/AsyncSpotify"

nav:
  - Overview: "index.md"
  - Reference:
      - Albums: "reference/albums.md"
      - Api: "reference/api.md"
      - Artists: "reference/artists.md"
      - Preferences: "reference/preferences.md"
      - Spotify Errors: "reference/spotify_errors.md"
      - Status Codes: "reference/status_codes.md"
  - Licence: "licence.md"

theme:
  name: "material"

extra_css:
  - custom.css


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/async_spotify
