site_name: "Async Spotify"
site_description: "Async wrapper in python for the spotify api"
site_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_name: "HuiiBuh/AsyncSpotify"

nav:
  - Overview: "index.md"
  - Examples: "examples.md"
  - Public API:
      - SpotifyApiClient: "public_api/spotify_api_client.md"
      - Preferences: "public_api/preferences.md"
      - Spotify Errors: "public_api/spotify_errors.md"
      - Endpoints: "public_api/endpoints.md"
      - Authorization Token: "public_api/authorization_token.md"

  - Licence: "licence.md"

theme:
  name: "material"
  language: en

  icon:
    logo: fontawesome/brands/spotify
    repo: fontawesome/brands/github
  favicon: https://upload.wikimedia.org/wikipedia/commons/9/9b/Font_Awesome_5_brands_spotify.svg

extra_css:
  - custom.css


markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/async_spotify
