site_name: "Async Spotify"
site_description: "Async wrapper in python for the spotify api"
site_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_name: "HuiiBuh/AsyncSpotify"

nav:
  - Overview: "index.md"
  - Examples: "EXAMPLES.md"
  - Public API:
      - Spotify Api Client: "public_api/spotify_api_client.md"
      - Preferences: "public_api/preferences.md"
      - Authentification: "public_api/authentification.md"
      - Spotify Errors: "public_api/spotify_errors.md"
      - Endpoints: "public_api/endpoints.md"
  - Private API:
      - Request Handler: "private_api/request_handler.md"
      - Status Classes: "private_api/status_classes.md"
      - URLS: "private_api/url.md"
  - Tests: "STUFF.md"
  - Licence: "LICENCE.md"

theme:
  name: "material"
  language: en

  icon:
    logo: fontawesome/brands/spotify
    repo: fontawesome/brands/github
  favicon: https://upload.wikimedia.org/wikipedia/commons/9/9b/Font_Awesome_5_brands_spotify.svg

extra_css:
  - custom.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true

plugins:
  - search
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/async_spotify
