site_name: "Async Spotify"
site_description: "Async wrapper in python for the spotify api"
site_url: "https://huiibuh.github.io/AsyncSpotify/"
repo_url: "https://github.com/HuiiBuh/AsyncSpotify"
repo_name: "HuiiBuh/AsyncSpotify"

nav:
  - Overview: "index.md"
  - Examples: "EXAMPLES.md"
  - Public API:
      - Spotify Api Client: "public_api/spotify_api_client.md"
      - Authentification: "public_api/authentification.md"
      - Token Renew Hook: "public_api/token_renew_class.md"
      - Spotify Errors: "public_api/spotify_errors.md"
      - Endpoints:
          - "public_api/endpoints/overview.md"
          - "public_api/endpoints/albums.md"
          - "public_api/endpoints/artists.md"
          - "public_api/endpoints/browse.md"
          - "public_api/endpoints/episodes.md"
          - "public_api/endpoints/follow.md"
          - "public_api/endpoints/library.md"
          - "public_api/endpoints/personalization.md"
          - "public_api/endpoints/player.md"
          - "public_api/endpoints/playlists.md"
          - "public_api/endpoints/search.md"
          - "public_api/endpoints/shows.md"
          - "public_api/endpoints/tracks.md"
          - "public_api/endpoints/user.md"
  - Reference:
      - Error Message: "reference/error_message.md"
      - Request Handler: "reference/request_handler.md"
      - Status Classes: "reference/status_classes.md"
      - URLS: "reference/url.md"
  - Tests: "STUFF.md"
  - Licence: "LICENCE.md"

theme:
  name: "material"
  language: en

  features:
    - instant

  palette:
    scheme: preference
    primary: green
    accent: green

  icon:
    logo: material/spotify
    repo: material/git
  favicon: https://upload.wikimedia.org/wikipedia/commons/9/9b/Font_Awesome_5_brands_spotify.svg

extra_css:
  - custom.css

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - pymdownx.superfences
  - pymdownx.emoji
  - toc:
      permalink: true

extra:
  social:
    - icon: fontawesome/brands/github-alt
      link: https://github.com/huiibuh

plugins:
  - search
  - git-revision-date-localized
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          rendering:
            show_source: true
      watch:
        - src/async_spotify
