name: Codecoverage
on:
  push:
    branches:
      - master
  watch:
    types: [started]
jobs:
  run:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix: 
        os: [ubuntu-latest, macos-latest, windows-latest]
    if: github.actor == github.event.repository.owner.login
    steps:
    - uses: actions/checkout@master
    - name: Setup Python  
      uses: actions/setup-python@master
      with:
        python-version: 3.8
    - name: Generate coverage report
      run: |
        pip install pytest
        pip install pytest-cov
        pip install -r requirements.dev.txt
        pytest --cov=async_spotify src/test --cov-report=xml
    - name: Upload coverage to Codecov  
      uses: codecov/codecov-action@v1.0.5
      with:
        token: ${{ secrets.CODECOV_TOKEN }}
        file: ./coverage.xml
        flags: unittests
        name: codecov-spotify-api
        fail_ci_if_error: true
